# Configure Terraform
terraform {
  required_version = ">= 1.0"
  
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# Create a directory
resource "local_file" "welcome" {
  content  = var.welcome_message
  filename = "${path.module}/terraform-files/welcome.txt"
}

# Create a JSON file with structured data
resource "local_file" "info" {
  content = jsonencode({
    project     = var.project_name
    environment = var.environment
    created_at  = timestamp()
    terraform_version = "1.0+"
  })
  filename = "${path.module}/terraform-files/info.json"
}

# Create a configuration file
resource "local_file" "config" {
  content  = <<-EOT
    # Configuration File
    # Generated by Terraform
    
    Project: ${var.project_name}
    Environment: ${var.environment}
    
    [Settings]
    enable_logging=true
    debug_mode=${var.environment == "dev" ? "true" : "false"}
    
    [Metadata]
    created_by=Terraform
    purpose=Learning Infrastructure as Code
  EOT
  filename = "${path.module}/terraform-files/config.ini"
}

# Create a README file in the terraform-files directory
resource "local_file" "readme" {
  content  = <<-EOT
    # Terraform Generated Files
    
    This directory contains files generated by Terraform for learning purposes.
    
    ## Files
    - welcome.txt: A simple welcome message
    - info.json: Project information in JSON format
    - config.ini: Sample configuration file
    - README.md: This file
    
    ## Warning
    These files are managed by Terraform. Manual changes may be overwritten!
    
    To modify these files, update the Terraform configuration and run:
    ```
    terraform apply
    ```
    
    To remove these files, run:
    ```
    terraform destroy
    ```
  EOT
  filename = "${path.module}/terraform-files/README.md"
}
